data:
  trainpath: /mounts/Datasets3/2024-2025-ChallengePlankton/train
  testpath: /mounts/Datasets3/2024-2025-ChallengePlankton/test
  batch_size: 4
  num_workers: 8
  valid_ratio: 0.2
  patch_size: 512
  stride: 128

optim:
  algo: Lion
  params:
    lr: 0.0001
    weight_decay: 0.0005
    betas: [0.9, 0.95]
    # momentum: 0.9

nepochs: 100
loss: 
  name: DiceFocalLoss
  params:
     alpha: [.2, .8]
     gamma: 2.5
     dice_weight: 2.
     focal_weight: 8.


logging:
  wandb: 
    project: Plankton
    entity: huyvan1337
  logdir: "/usr/users/sdim/sdim_22/team-6-kaggle-challenge-deep-learning/pytorch_template_code-main/model_logs"  # Better to provide the fullpath, especially on the cluster

model:
  class: UnetPlus
  threshold: .65

prediction:
  dir: "./predictions/"
