data:
  trainpath: /mounts/Datasets3/2024-2025-ChallengePlankton/train
  testpath: /mounts/Datasets3/2024-2025-ChallengePlankton/test
  batch_size: 32
  num_workers: 8
  valid_ratio: 0.2
  patch_size: 256
  stride: 128

optim:
  algo: AdamW
  params:
    lr: 0.0001
    weight_decay: 0.001
    # momentum: 0.9

nepochs: 100
loss: 
  name: DiceFocalLoss
  params:
     alpha: [.3, .7]
     gamma: 2.5
     dice_weight: 1.
     focal_weight: 10.


logging:
  wandb: 
    project: Plankton
    entity: huyvan1337
  logdir: "/usr/users/sdim/sdim_22/team-6-kaggle-challenge-deep-learning/pytorch_template_code-main/model_logs"  # Better to provide the fullpath, especially on the cluster

model:
  class: UnetPlus
  threshold: .5

prediction:
  dir: "./predictions/"

    
