data:
  trainpath: /mounts/Datasets3/2024-2025-ChallengePlankton/train
  testpath: /mounts/Datasets3/2024-2025-ChallengePlankton/test
  batch_size: 32
  num_workers: 4
  valid_ratio: 0.2

optim:
  algo: SGD
  params:
    lr: 0.001

nepochs: 25
loss: "BCEWithLogitsLoss"

logging:
  wandb: 
    project: Segmenting_Living_Organisms
    entity: huyvan1337
  logdir: "./logs"  # Better to provide the fullpath, especially on the cluster

model:
  class: UNet

prediction:
  dir: "./predictions/"

    
